version: "3.2"
services:
  backend:
    build:
      context: "./docker/phpApache/"
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: backend
    volumes:
      - ./backend/:/var/www/html
      - ./docker/phpApache/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
        default:
            ipv4_address: 172.18.0.3
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
volumes:
  mysql-data:
